### PR TITLE
fix: defer Claude MCP wait

### LINKED ISSUE #76: Move Claude MCP wait to first-message time (lazy init)
## User Request

Claude e2e MCP tests fail because the Claude daemon calls `waitForMCPServers` eagerly at daemon construction time. The MCP sidecar container starts slowly, and the daemon's context can be cancelled before the 120s timer expires, causing "daemon init failed".

### Root Cause
In `internal/daemon/claude.go`, `waitForMCPServers` is called during `newClaudeDaemon()` construction. The Codex daemon calls it lazily — only when the first message arrives (in `ensureCodexThread()`), giving the MCP sidecar plenty of time to start.

### Fix
Move the `waitForMCPServers` call from `newClaudeDaemon()` to the message handler — call it lazily on the first message, matching the Codex pattern. This can be done with a `sync.Once` or a simple boolean flag to ensure it's only called once.

**Pattern to follow:** Look at how Codex does it in `ensureCodexThread()` — the MCP wait happens when the first thread is created, not at daemon construction.

### Verification
- `go build ./...`
- `go vet ./...`
- `go test ./...`

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- move MCP server readiness check to Claude message handling
- track Claude MCP readiness to avoid repeated waits

## Testing
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go build ./...
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go vet ./...
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go test ./...

Closes #76

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go build ./...
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go vet ./...
- GOPRIVATE=github.com/agynio/* GONOSUMDB=github.com/agynio/* GONOPROXY=github.com/agynio/* go test ./...

Tests: passed 7, failed 0, skipped 0.
Lint: go vet reported no issues.

File: internal/daemon/claude.go [hunk 1]
```diff
@@ -77,6 +72,19 @@ func newClaudeDaemon(ctx context.Context, cfg config.Config, version string) (*D
...
+func (d *Daemon) ensureClaudeReady(ctx context.Context) error {
+	d.claudeReadyMu.Lock()
+	defer d.claudeReadyMu.Unlock()
+	if d.claudeReady {
+		return nil
+	}
+	if err := waitForMCPServers(ctx, d.cfg.MCPServers, mcpReadyTimeout); err != nil {
+		return err
+	}
+	d.claudeReady = true
```
Comment (noa-lucent) [inline internal/daemon/claude.go:84]: [minor] Consider adding a unit test for `ensureClaudeReady`. The existing tests implicitly exercise it (with an empty `MCPServers` slice), but the retry-on-failure semantic (returning an error without setting `claudeReady`, so the next message retries) is the key behavior this PR introduces and is currently untested. A test with a fake `waitForMCPServers` that fails once then succeeds would cover this nicely.

That said, the logic is straightforward and correct — not blocking the PR on this.

**Review by noa-lucent — APPROVED** [review]
Clean change that correctly defers the MCP readiness check from daemon construction to first-message time, matching the Codex pattern. 

The mutex+bool approach over `sync.Once` is the right call here — it allows retry on transient MCP failures rather than permanently marking the check as done.

One minor suggestion for test coverage on the new method; not blocking.
