### PR TITLE
fix(daemon): skip idle workload touches

### LINKED ISSUE #97: Bug: keepalive touches workload while idle, preventing orchestrator idle_timeout stop
## User report

Orchestrator loops forever with `desired=0 actual=1 started=0 stopped=0` even well past `idle_timeout`.

Example log:

```text
reconciler: cycle complete - desired=0 actual=1 started=0 stopped=0
```

## Expected

When a workload has no desired work (no unacked messages) and is idle past `idle_timeout`, it should be stopped/removed by the orchestrator.

Architecture reference (`agynio/architecture`, agents-orchestrator doc): idleness is measured from `Workload.last_activity_at`, which should be refreshed by `agynd` via `TouchWorkload` **only while actively processing**, and should stop when idle.

## Root cause

`agynd` currently refreshes keepalive unconditionally on a 10s ticker, even when the agent is idle. This keeps `last_activity_at` perpetually fresh, so orchestrator's idle-timeout stop condition never becomes true.

### Fix

Gate `TouchWorkload` behind a `processing` flag so keepalive only runs during active message processing:

- Add an `atomic.Bool processing` to `Daemon`.
- In `syncMessages`, set `processing=true` for the duration of the sync/handle loop, and ensure it is set back to `false` on return.
- In the keepalive loop, skip `TouchWorkload` when `processing=false`.

### Tests

Add unit tests:
- keepalive does **not** call `TouchWorkload` when idle (`processing=false`)
- keepalive **does** call `TouchWorkload` when processing (`processing=true`)

## Rollout

After merging, cut a new patch release (v0.14.x) so agent init images can bump the bundled agynd version.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- add processing state to gate workload keepalive touches
- skip touching workloads when the daemon is idle
- add tests covering processing vs idle keepalive behavior

## Testing
- buf generate buf.build/agynio/api --path agynio/api/gateway/v1 --include-imports
- go test ./...
- go vet ./...

Closes #97

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- buf generate buf.build/agynio/api --path agynio/api/gateway/v1 --include-imports
- go test ./...
  - passed: 7, failed: 0, skipped: 1
- go vet ./...
  - lint: no issues

File: internal/daemon/keepalive_test.go [hunk 1]
```diff
@@ -113,6 +114,31 @@ func TestTouchActiveWorkloadCallsTouch(t *testing.T) {
...
+	daemon := &Daemon{
+		cfg:     config.Config{AgentID: uuid.MustParse(testAgentID)},
+		runners: fake,
+	}
+	touched, err := daemon.touchActiveWorkload(context.Background(), "thread-1")
+	if err != nil {
+		t.Fatalf("expected no error, got %v", err)
+	}
+	if touched {
+		t.Fatal("expected no workload to be touched")
```
Comment (noa-lucent) [inline internal/daemon/keepalive_test.go:135]: [nit] Consider asserting `fake.listCalls == 0` here as well. Since the early return in `touchActiveWorkload` skips `findActiveWorkload` entirely, verifying that no list RPCs were made would strengthen the test by confirming the short-circuit behavior, not just the absence of touch calls.

**Review by noa-lucent — APPROVED** [review]
Clean, well-scoped fix that matches the issue specification precisely. The `atomic.Bool` gating approach is the right tool for cross-goroutine coordination here, the defer ordering is correct (processing reset before mutex unlock), and the tests cover both the idle-skip and active-touch paths. One minor nit on test tightness left inline. LGTM.
